detect_duration: 10
camera_id: 0
enable_multithread_detect: true
retrack_queue_size: 10
fps: 75
send_posedata_udp: true
port: 4242
udp_host: 127.000.000.1
use_ft: false
use_npclient: false
cov_Q_lm: 0.0037153522909717253
cov_Q_fsa: 0.0037153522909717253
cov_T: 0.041627660370093647
cov_V: 9.120108393559109
cov_W: 9.120108393559109
ekf_predict_dt: 0.01
use_ekf: false
disp_duration: 30
disp_max_series_size: 1000
detect_method: 0
fsa_pnp_mixture_rate: 0.45000000000000001
hotkey_joystick_name0: Saitek Pro Flight X-55 Rhino Throttle
hotkey_joystick_button0: 1
hotkey_joystick_name1: ""
hotkey_joystick_button1: 0
landmark_detect_method: 0
pitch_offset_fsa_pnp: 0.219911486