detect_duration: 2
camera_id: 0
enable_multithread_detect: true
retrack_queue_size: 10
fps: 30
send_posedata_udp: true
port: 4242
udp_host: "192.168.1.22"

use_ft: false
use_npclient: false
cov_Q: 0.1
cov_T: 0.05
cov_V: 10.0
cov_W: 40.0
ekf_predict_dt: 0.01
use_ekf: false
disp_duration: 30
disp_max_series_size: 1000

detect_method: 0